language: node_js
cache: npm

node_js:
  - "10"
  - "12"
  - "node"

before_install:
  - npm install coveralls

script:
  - npm test
  - npm run test-cov

after_script:
  - nyc report --reporter=text-lcov | coveralls
